export const SOCKET_EVENT = {
  CONNECTION: 'connect',
  DISCONNECT: 'disconnect',
  DISCONNECTING: 'DISCONNECTING',
  USER_JOINROOM: 'USER_JOINROOM',
  USER_LEAVEROOM: 'USER_LEAVEROOM',
  USER_NEWMESSAGE: 'USER_NEWMESSAGE',
  ROOM_NEWMESSAGE: 'ROOM_NEWMESSAGE',
  ROOM_JOIN: 'ROOM_JOIN'
};
