export const SOCKET_EVENT = {
  CONNECTION: 'CONNECTION',
  DISCONNECT: 'DISCONNECT',
  DISCONNECTING: 'DISCONNECTING',
  USER_JOINROOM: 'USER_JOINROOM',
  USER_LEAVEROOM: 'USER_LEAVEROOM',
  USER_NEWMESSAGE: 'USER_NEWMESSAGE'
};
