// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/app-provider.vue')['default']
    Avatar: typeof import('./../components/user/avatar.vue')['default']
    FadeTransition: typeof import('./../components/ui/transitions/fade-transition.vue')['default']
    Header: typeof import('./../components/layout/header.vue')['default']
    HeaderRoomList: typeof import('./../components/header/header-room-list.vue')['default']
    HeaderRoomView: typeof import('./../components/header/header-room-view.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    InputText: typeof import('./../components/ui/input/input-text.vue')['default']
    LayoutHeader: typeof import('./../components/layout/layout-header.vue')['default']
    Login: typeof import('./../components/auth/login.vue')['default']
    MessageLayout: typeof import('./../components/room/message/message-layout.vue')['default']
    Nav: typeof import('./../components/layout/nav.vue')['default']
    Plain: typeof import('./../components/ui/button/plain.vue')['default']
    PlainButton: typeof import('./../components/ui/button/plain-button.vue')['default']
    Register: typeof import('./../components/auth/register.vue')['default']
    RoomList: typeof import('./../components/room/list/room-list.vue')['default']
    RoomView: typeof import('./../components/room/view/room-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./../components/ui/section/section-heading/section-heading.vue')['default']
    SectionProvider: typeof import('./../components/ui/section/section-provider.vue')['default']
    SocketProvider: typeof import('./../components/socket-provider.vue')['default']
    StatusButton: typeof import('./../components/ui/button/status-button.vue')['default']
    SuccessButton: typeof import('./../components/ui/button/success-button.vue')['default']
    UserList: typeof import('./../components/room/list/user-list.vue')['default']
    UserProfileProvider: typeof import('./../components/user/user-profile-provider.vue')['default']
  }
}
